name: Build Android de Bruin Sistemas
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['flutter/lib/**', 'flutter/pubspec.yaml']

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter clean
        flutter pub get

    - name: Build Android APK
      run: flutter build apk --release --verbose

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-android
        path: flutter/build/app/outputs/flutter-apk/app-release.apkname: Build Android de Bruin Sistemas
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['flutter/lib/**', 'flutter/pubspec.yaml']

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter clean
        flutter pub get

    - name: Build Android APK
      run: flutter build apk --release --verbose

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-android
        path: flutter/build/app/outputs/flutter-apk/app-release.apk
