name: de bruin personalização
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'windows'
        type: choice
        options:
        - windows
        - android
        - linux
        - macos
  push:
    branches: [ main ]
    paths: ['flutter/lib/**', 'flutter/pubspec.yaml']

jobs:
  build-windows:
    if: github.event.inputs.platform == 'windows' || github.event_name == 'push'
    runs-on: windows-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'

    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter clean
        flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-windows
        path: flutter/build/windows/x64/runner/Release/
