name: de bruin personalização
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'android'
        type: choice
        options:
        - android
        - linux
        - macos
  push:
    branches: [ main ]
    paths: ['flutter/lib/**', 'flutter/pubspec.yaml']

jobs:
  # build-windows:
  #   if: github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all' || github.event_name == 'push'
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       working-directory: flutter
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive
  #       fetch-depth: 0

  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       channel: 'stable'

  #   - name: Install Rust
  #     uses: dtolnay/rust-toolchain@stable
  #     with:
  #       toolchain: stable

  #   - name: Setup Rust cache
  #     uses: Swatinem/rust-cache@v2

  #   - name: Install dependencies
  #     run: |
  #       flutter doctor -v
  #       flutter clean
  #       flutter pub get

  #   - name: Build Windows
  #     run: flutter build windows --release --verbose

  #   - name: Upload Windows Build
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: de-bruin-sistemas-windows
  #       path: flutter/build/windows/x64/runner/Release/

  build-android:
    if: github.event.inputs.platform == 'android' || github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter clean
        flutter pub get

    - name: Build Android APK
      run: flutter build apk --release --verbose

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-android
        path: flutter/build/app/outputs/flutter-apk/app-release.apk

  build-macos:
    if: github.event.inputs.platform == 'macos'
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build macOS
      run: flutter build macos --release

    - name: Upload macOS Build
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-macos
        path: build/macos/Build/Products/Release/

  build-linux:
    if: github.event.inputs.platform == 'linux'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Linux
      run: flutter build linux --release

    - name: Upload Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: de-bruin-sistemas-linux
        path: build/linux/x64/release/bundle/
