name: de bruin personalização
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Plataforma'
        required: true
        default: 'windows'
        type: choice
        options:
        - windows
        - android
  push:
    branches: [ main ]
    paths: ['flutter/**']

jobs:
  build-windows:
    if: github.event.inputs.platform == 'windows' || github.event_name == 'push'
    runs-on: windows-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
    - run: flutter pub get
    - run: flutter build windows --release
    - uses: actions/upload-artifact@v4
      with:
        name: de-bruin-windows
        path: flutter/build/windows/x64/runner/Release/

  build-android:
    if: github.event.inputs.platform == 'android'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter build apk --release
    - uses: actions/upload-artifact@v4
      with:
        name: de-bruin-android
        path: flutter/build/app/outputs/flutter-apk/app-release.apk
